[auth]
site_url = "https://subscriber.meuraki.com.sg"
additional_redirect_urls = ["https://subscriber.meuraki.com.sg/pages/auth/callback"]

[auth.external.google]
enabled = true
client_id = "REDACTED_GOOGLE_CLIENT_ID"
secret = "REDACTED_GOOGLE_CLIENT_SECRET"
